In [2]:
import numpy as np
import pandas as pd

In [9]:
def gram_schmidt(A):
    rows,cols = A.shape
    result = np.zeros((rows,cols))

    for k in range(cols):
        curr_vec = A[:,k].astype(float).copy()

        if k > 0:
            for j in range(k):
                e_j = result[:, j]
                dot_product = np.dot(curr_vec, e_j)
                projection = dot_product * e_j
                curr_vec = curr_vec - projection

        vec_length = np.linalg.norm(curr_vec)
        # Taking care of Floating point representation error 
        if vec_length < 1e-10:
            raise ValueError("Vectors are not linearly independent!")
        result[:, k] = curr_vec / vec_length

    return result


In [10]:
if __name__ == "__main__":
    A = np.array([
        [1.0, 1.0, 1.0],
        [1e-4, 0.0, 0.0],
        [0.0, 1e-4, 0.0]
    ])
    result = gram_schmidt(A)      
 
    QtQ = result.T @ result                         # Q^T @ Q = Identity matrix
    print("Q^T @ Q ≈ I :", np.allclose(QtQ, np.eye(3)))
    print(np.round(QtQ, 6))

Q^T @ Q ≈ I : True
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]
